### ISSUE TITLE
When reach end of playlist, conplay reports error when next run

### ISSUE THREAD

**Issue by visionimpaired** [thp/mpg123#1]
When playing files using conplay and the last file in the playlist has completed, the bookmark is set to the last file and position. When next started an error is reported.

Is it possible to reset the bookmark if the end of the last file is reached?

**Comment by thp** [comment]
This is not the upstream repository of mpg123, please file issues at upstream's bug tracker at http://sourceforge.net/p/mpg123/bugs/
